### ISSUE TITLE
The validator crashes when AV1 is supplied without billing information

### ISSUE THREAD

**Issue by Arthur26** [swico/www.swiss-qr-invoice.org#10]
A Swiss QR Code with empty Bill information (line 32) but "eBill/B/peter@muster.ch" as AV1 (line 33) will crasch the validator with the error "Ein unbekannter Fehler ist aufgetreten (siehe js logs für mehr Details)"

**Comment by epsitec** [comment]
Good catch. I'll ask @QJonny to have a look too.

**Comment by QJonny** [comment]
Fixed, will be available in next release
