### ISSUE TITLE
Linefeed after filled AV2 parameter is reported as error

### ISSUE THREAD

**Issue by Arthur26** [swico/www.swiss-qr-invoice.org#11]
The FAQ ( https://www.paymentstandards.ch/en/shared/know-how/faq/qr.html ) question "How many lines (elements) does the Swiss QR Code contain?" states: "For the last filled data element, the final line break (CR/LF or LF) can be retained or omitted."

If I retain the final line break after the filled AV2 parameter (line 34) the validator shows an error.

**Comment by QJonny** [comment]
Fixed, will be available in next release

**Comment by QJonny** [comment]
Fixed, will be available in next version
