### ISSUE TITLE
Validator tools does not work

### ISSUE THREAD

**Issue by Tontontonio1981** [swico/www.swiss-qr-invoice.org#34]
Dear,

I'm trying to test some QR invoices with the validator tool. But all of them are rejected. I tested with many invoices of my suppliers and mine as well (and they all work with eBanking). But the validator said that the request failed.
Then it says to look at the log for more details. And it's not possible to see the log.

Any ideas about what is going on with https://www.swiss-qr-invoice.org/validator ?

**Comment by Tontontonio1981** [comment]
<img width="1025" alt="Capture d’écran 2022-04-06 à 09 24 54" src="https://user-images.githubusercontent.com/103101993/161920340-cf7372bc-b38e-4634-8aa3-e46e19037f70.png">

**Comment by QJonny** [comment]
Hello,

the QR validator works again. Sorry for the inconvenience!
