### ISSUE TITLE
QR-Code with beneficiary country code 'C' should be invalid

### ISSUE THREAD

**Issue by Arthur26** [swico/www.swiss-qr-invoice.org#6]
The Field Ctry (Country) of the creditor must always be of exact length 2, but the validator accpepts a country-code of lenght 1 (e.g. 'C' instead of 'CH').

**Comment by epsitec** [comment]
Thanks @Arthur26 for spotting this defect. We will update the validator accordingly.

**Comment by QJonny** [comment]
Fixed, will be available in next release
