### ISSUE TITLE
The validator does not escape the character \ correctly

### ISSUE THREAD

**Issue by Arthur26** [swico/www.swiss-qr-invoice.org#7]
The Documentation states: "Feldinhalte dürfen nicht die Zeichen «/» und «\» enthalten; diese müssen durch «\/» und «\\» ersetzt werden (Escape)."
But the validator evaluates e.g. the Rechnungsnummer of "//S1/10/123\\\\abc" erroneously as "123\\\\abc" and not as "123\\abc".

It also does not show an error when I use an invalid escape sequence like e.g. "//S1/10/123\\abc" or "//S1/10/123\\".

**Comment by epsitec** [comment]
Thank you @Arthur26 for spotting this :-)

You are right, the invoice reference should be displayed as `123\abc` in the summary view.
I'll ask my colleague Jonny Quarta to look into the invalid escape sequences such as `\a` and trailing escapes such as `123\`.

**Comment by QJonny** [comment]
Fixed, will be available in next release
