### ISSUE TITLE
Missing Field 'Bill information' is not validated correctly

### ISSUE THREAD

**Issue by Arthur26** [swico/www.swiss-qr-invoice.org#9]
The specification at https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf (Version Version 2.1 – 30.09.2019) states on page 29, that the field "Bill information" is optional (Letter O in column status), which means, the Field must mandatorily be delivered, but not necessarily filled (can be empty).

However, the validator accepts a Swiss QR Code without the Field "Bill information" as valid.

(Note, that most of Swiss QR Code examples in the given specification (Annex A: Examples) are not valid according to this rule)

**Comment by epsitec** [comment]
I'll ask Thomas Reske if the IGs are indeed correct or not.

**Comment by epsitec** [comment]
SIX (Karolina Suchowska) replied that this is covered by the [QR bill FAQ](https://www.paymentstandards.ch/en/shared/know-how/faq/qr.html):

> **How many lines (elements) does the Swiss QR Code contain?**
>
> The QR code always contains a minimum of 31 lines and a maximum of 34 lines (when using "Billing information" and 2x "Alternative procedure parameters"). For the last filled data element, the final line break (CR/LF or LF) can be retained or omitted.
>
> If a Swiss QR Code contains only payment information, the last filled element is always the "Trailer" element with the character string EPD in line 31.

I feel that the IGs should be clarified with respect to the meaning of _optional fields_ when these are found after the `EPD`.

**Comment by epsitec** [comment]
I've got the confirmation that SIX will update the Implementation Guidelines in a future revision.

**Comment by epsitec** [comment]
The behavior of the validator is correct and I'll close this issue.

**Comment by Arthur26** [comment]
Thanks for this clarification.
